package am.ik.codepoints.collection;

import am.ik.codepoints.CodePoints;

/**
 * 0x3041-0x3093
 */
public final class HiraganaLetter_JISX0208CodePoints extends CodePoints.Wrapper {

    public HiraganaLetter_JISX0208CodePoints() {
        super(0x3041 /* HIRAGANA LETTER SMALL A */,
                0x3042 /* HIRAGANA LETTER A */,
                0x3043 /* HIRAGANA LETTER SMALL I */,
                0x3044 /* HIRAGANA LETTER I */,
                0x3045 /* HIRAGANA LETTER SMALL U */,
                0x3046 /* HIRAGANA LETTER U */,
                0x3047 /* HIRAGANA LETTER SMALL E */,
                0x3048 /* HIRAGANA LETTER E */,
                0x3049 /* HIRAGANA LETTER SMALL O */,
                0x304A /* HIRAGANA LETTER O */,
                0x304B /* HIRAGANA LETTER KA */,
                0x304C /* HIRAGANA LETTER GA */,
                0x304D /* HIRAGANA LETTER KI */,
                0x304E /* HIRAGANA LETTER GI */,
                0x304F /* HIRAGANA LETTER KU */,
                0x3050 /* HIRAGANA LETTER GU */,
                0x3051 /* HIRAGANA LETTER KE */,
                0x3052 /* HIRAGANA LETTER GE */,
                0x3053 /* HIRAGANA LETTER KO */,
                0x3054 /* HIRAGANA LETTER GO */,
                0x3055 /* HIRAGANA LETTER SA */,
                0x3056 /* HIRAGANA LETTER ZA */,
                0x3057 /* HIRAGANA LETTER SI */,
                0x3058 /* HIRAGANA LETTER ZI */,
                0x3059 /* HIRAGANA LETTER SU */,
                0x305A /* HIRAGANA LETTER ZU */,
                0x305B /* HIRAGANA LETTER SE */,
                0x305C /* HIRAGANA LETTER ZE */,
                0x305D /* HIRAGANA LETTER SO */,
                0x305E /* HIRAGANA LETTER ZO */,
                0x305F /* HIRAGANA LETTER TA */,
                0x3060 /* HIRAGANA LETTER DA */,
                0x3061 /* HIRAGANA LETTER TI */,
                0x3062 /* HIRAGANA LETTER DI */,
                0x3063 /* HIRAGANA LETTER SMALL TU */,
                0x3064 /* HIRAGANA LETTER TU */,
                0x3065 /* HIRAGANA LETTER DU */,
                0x3066 /* HIRAGANA LETTER TE */,
                0x3067 /* HIRAGANA LETTER DE */,
                0x3068 /* HIRAGANA LETTER TO */,
                0x3069 /* HIRAGANA LETTER DO */,
                0x306A /* HIRAGANA LETTER NA */,
                0x306B /* HIRAGANA LETTER NI */,
                0x306C /* HIRAGANA LETTER NU */,
                0x306D /* HIRAGANA LETTER NE */,
                0x306E /* HIRAGANA LETTER NO */,
                0x306F /* HIRAGANA LETTER HA */,
                0x3070 /* HIRAGANA LETTER BA */,
                0x3071 /* HIRAGANA LETTER PA */,
                0x3072 /* HIRAGANA LETTER HI */,
                0x3073 /* HIRAGANA LETTER BI */,
                0x3074 /* HIRAGANA LETTER PI */,
                0x3075 /* HIRAGANA LETTER HU */,
                0x3076 /* HIRAGANA LETTER BU */,
                0x3077 /* HIRAGANA LETTER PU */,
                0x3078 /* HIRAGANA LETTER HE */,
                0x3079 /* HIRAGANA LETTER BE */,
                0x307A /* HIRAGANA LETTER PE */,
                0x307B /* HIRAGANA LETTER HO */,
                0x307C /* HIRAGANA LETTER BO */,
                0x307D /* HIRAGANA LETTER PO */,
                0x307E /* HIRAGANA LETTER MA */,
                0x307F /* HIRAGANA LETTER MI */,
                0x3080 /* HIRAGANA LETTER MU */,
                0x3081 /* HIRAGANA LETTER ME */,
                0x3082 /* HIRAGANA LETTER MO */,
                0x3083 /* HIRAGANA LETTER SMALL YA */,
                0x3084 /* HIRAGANA LETTER YA */,
                0x3085 /* HIRAGANA LETTER SMALL YU */,
                0x3086 /* HIRAGANA LETTER YU */,
                0x3087 /* HIRAGANA LETTER SMALL YO */,
                0x3088 /* HIRAGANA LETTER YO */,
                0x3089 /* HIRAGANA LETTER RA */,
                0x308A /* HIRAGANA LETTER RI */,
                0x308B /* HIRAGANA LETTER RU */,
                0x308C /* HIRAGANA LETTER RE */,
                0x308D /* HIRAGANA LETTER RO */,
                0x308E /* HIRAGANA LETTER SMALL WA */,
                0x308F /* HIRAGANA LETTER WA */,
                0x3090 /* HIRAGANA LETTER WI */,
                0x3091 /* HIRAGANA LETTER WE */,
                0x3092 /* HIRAGANA LETTER WO */, 0x3093 /* HIRAGANA LETTER N */);
    }
}
