package am.ik.codepoints.collection;

import am.ik.codepoints.CodePoints;

/**
 * 0x30A1-0x30F2
 */
public final class KatakanaLetter_JISX0208CodePoints extends CodePoints.Wrapper {

    public KatakanaLetter_JISX0208CodePoints() {
        super(0x30A1 /* KATAKANA LETTER SMALL A */,
                0x30A2 /* KATAKANA LETTER A */,
                0x30A3 /* KATAKANA LETTER SMALL I */,
                0x30A4 /* KATAKANA LETTER I */,
                0x30A5 /* KATAKANA LETTER SMALL U */,
                0x30A6 /* KATAKANA LETTER U */,
                0x30A7 /* KATAKANA LETTER SMALL E */,
                0x30A8 /* KATAKANA LETTER E */,
                0x30A9 /* KATAKANA LETTER SMALL O */,
                0x30AA /* KATAKANA LETTER O */,
                0x30AB /* KATAKANA LETTER KA */,
                0x30AC /* KATAKANA LETTER GA */,
                0x30AD /* KATAKANA LETTER KI */,
                0x30AE /* KATAKANA LETTER GI */,
                0x30AF /* KATAKANA LETTER KU */,
                0x30B0 /* KATAKANA LETTER GU */,
                0x30B1 /* KATAKANA LETTER KE */,
                0x30B2 /* KATAKANA LETTER GE */,
                0x30B3 /* KATAKANA LETTER KO */,
                0x30B4 /* KATAKANA LETTER GO */,
                0x30B5 /* KATAKANA LETTER SA */,
                0x30B6 /* KATAKANA LETTER ZA */,
                0x30B7 /* KATAKANA LETTER SI */,
                0x30B8 /* KATAKANA LETTER ZI */,
                0x30B9 /* KATAKANA LETTER SU */,
                0x30BA /* KATAKANA LETTER ZU */,
                0x30BB /* KATAKANA LETTER SE */,
                0x30BC /* KATAKANA LETTER ZE */,
                0x30BD /* KATAKANA LETTER SO */,
                0x30BE /* KATAKANA LETTER ZO */,
                0x30BF /* KATAKANA LETTER TA */,
                0x30C0 /* KATAKANA LETTER DA */,
                0x30C1 /* KATAKANA LETTER TI */,
                0x30C2 /* KATAKANA LETTER DI */,
                0x30C3 /* KATAKANA LETTER SMALL TU */,
                0x30C4 /* KATAKANA LETTER TU */,
                0x30C5 /* KATAKANA LETTER DU */,
                0x30C6 /* KATAKANA LETTER TE */,
                0x30C7 /* KATAKANA LETTER DE */,
                0x30C8 /* KATAKANA LETTER TO */,
                0x30C9 /* KATAKANA LETTER DO */,
                0x30CA /* KATAKANA LETTER NA */,
                0x30CB /* KATAKANA LETTER NI */,
                0x30CC /* KATAKANA LETTER NU */,
                0x30CD /* KATAKANA LETTER NE */,
                0x30CE /* KATAKANA LETTER NO */,
                0x30CF /* KATAKANA LETTER HA */,
                0x30D0 /* KATAKANA LETTER BA */,
                0x30D1 /* KATAKANA LETTER PA */,
                0x30D2 /* KATAKANA LETTER HI */,
                0x30D3 /* KATAKANA LETTER BI */,
                0x30D4 /* KATAKANA LETTER PI */,
                0x30D5 /* KATAKANA LETTER HU */,
                0x30D6 /* KATAKANA LETTER BU */,
                0x30D7 /* KATAKANA LETTER PU */,
                0x30D8 /* KATAKANA LETTER HE */,
                0x30D9 /* KATAKANA LETTER BE */,
                0x30DA /* KATAKANA LETTER PE */,
                0x30DB /* KATAKANA LETTER HO */,
                0x30DC /* KATAKANA LETTER BO */,
                0x30DD /* KATAKANA LETTER PO */,
                0x30DE /* KATAKANA LETTER MA */,
                0x30DF /* KATAKANA LETTER MI */,
                0x30E0 /* KATAKANA LETTER MU */,
                0x30E1 /* KATAKANA LETTER ME */,
                0x30E2 /* KATAKANA LETTER MO */,
                0x30E3 /* KATAKANA LETTER SMALL YA */,
                0x30E4 /* KATAKANA LETTER YA */,
                0x30E5 /* KATAKANA LETTER SMALL YU */,
                0x30E6 /* KATAKANA LETTER YU */,
                0x30E7 /* KATAKANA LETTER SMALL YO */,
                0x30E8 /* KATAKANA LETTER YO */,
                0x30E9 /* KATAKANA LETTER RA */,
                0x30EA /* KATAKANA LETTER RI */,
                0x30EB /* KATAKANA LETTER RU */,
                0x30EC /* KATAKANA LETTER RE */,
                0x30ED /* KATAKANA LETTER RO */,
                0x30EE /* KATAKANA LETTER SMALL WA */,
                0x30EF /* KATAKANA LETTER WA */,
                0x30F0 /* KATAKANA LETTER WI */,
                0x30F1 /* KATAKANA LETTER WE */,
                0x30F2 /* KATAKANA LETTER WO */, 0x30F3 /* KATAKANA LETTER N */);
    }
}
